let localization = {
  EN: {
    title: "Registration",
    firstname: "First Name",
    lastname: "Last Name",
    email: "Email",
    phone: "Phone number",
    conditions: { 0: "I have read and accept the", 1: "Customer Agreement" },
    age: "I hereby confirm that I am at least 18 years old",
    button: "Start now!",
    error: {
      required: "This is a required field",
      email: "Please enter a valid email address",
      phone: "Please enter a valid phone number",
    },
  },

  DE: {
    title: "Die registrierung",
    firstname: "Vorname",
    lastname: "Nachname",
    email: "E-mail",
    phone: "Telefonnummer",
    conditions: { 0: "I have read and accept the", 1: "Customer Agreement" },
    age: "I hereby confirm that I am at least 18 years old",
    button: "Jetzt anfangen",
    error: {
      required: "Das ist ein Pflichtfeld",
      email: "Bitte geben Sie eine gültige E-Mail-Adresse ein",
      phone: "Bitte geben Sie eine gültige Telefonnummer ein",
    },
  }, // -- тут же AT, CH, LI, LU
  DK: {
    firstname: "Navn",
    lastname: "Efternavn",
    email: "E-mail",
    phone: "Telefonnummer",
    conditions: { 0: "I have read and accept the", 1: "Customer Agreement" },
    age: "I hereby confirm that I am at least 18 years old",
    button: "Start nu!",
    error: {
      required: "Dette er et obligatorisk felt",
      email: "Indtast venligst en gyldig e-mailadresse",
      phone: "Indtast venligst et gyldigt telefonnummer",
    },
  },
  ES: {
    title: "Registro",
    firstname: "Nombre",
    lastname: "Apellido",
    email: "E-mail",
    phone: "Número de teléfono",
    conditions: { 0: "I have read and accept the", 1: "Customer Agreement" },
    age: "I hereby confirm that I am at least 18 years old",
    button: "¡Empezar ahora!",
    error: {
      required: "Este es un campo obligatorio",
      email: "Por favor, introduce una dirección de correo electrónico válida",
      phone: "Por favor ingrese un número de teléfono válido",
    },
  },
  FI: {
    firstname: "Etunimi",
    lastname: "Sukunimi",
    email: "E-mail",
    phone: "Puhelinnumero",
    conditions: { 0: "I have read and accept the", 1: "Customer Agreement" },
    age: "I hereby confirm that I am at least 18 years old",
    button: "Aloita nyt!",
    error: {
      required: "Tämä on pakollinen kenttä",
      email: "Ole hyvä ja syötä toimiva sähköpostiosoite",
      phone: "Ole hyvä ja näppäile voimassaoleva puhelinnumero",
    },
  },
  FR: {
    title: "Enregistrement",
    firstname: "Prénom",
    lastname: "Nom de famille",
    email: "Email",
    phone: "Numéro de téléphone",
    conditions: { 0: "I have read and accept the", 1: "Customer Agreement" },
    age: "I hereby confirm that I am at least 18 years old",
    button: "Commencez maintenant!",
    error: {
      required: "Ceci est un champ obligatoire",
      email: "S'il vous plaît, mettez une adresse email valide",
      phone: "S'il vous plaît entrer un numéro de téléphone valide",
    },
  },
  IS: {
    firstname: "Fyrsta nafn",
    lastname: "Eftirnafn",
    email: "Netfang",
    phone: "Símanúmer",
    conditions: { 0: "I have read and accept the", 1: "Customer Agreement" },
    age: "I hereby confirm that I am at least 18 years old",
    button: "Byrjaðu núna!",
    error: {
      required: "Þetta er krafist reitur",
      email: "Vinsamlegast sláðu inn gilt netfang",
      phone: "Vinsamlegast sláðu inn gilt símanúmer",
    },
  },
  IT: {
    title: "Registrazione",
    firstname: "Nome di battesimo",
    lastname: "Cognome",
    email: "E-mail",
    phone: "Numero di telefono",
    conditions: { 0: "I have read and accept the", 1: "Customer Agreement" },
    age: "I hereby confirm that I am at least 18 years old",
    button: "Avviare ora!",
    error: {
      required: "Questo è un campo obbligatorio",
      email: "Si prega di inserire un indirizzo email valido",
      phone: "Si prega di inserire un numero di telefono valido",
    },
  },
  NL: {
    firstname: "Voornaam",
    lastname: "Achternaam",
    email: "E-mail",
    phone: "Telefoonnummer",
    conditions: { 0: "I have read and accept the", 1: "Customer Agreement" },
    age: "I hereby confirm that I am at least 18 years old",
    button: "Begin nu!",
    error: {
      required: "Dit is een verplicht veld",
      email: "Gelieve een geldig e-mailadres in te geven",
      phone: "Voer alstublieft een geldig telefoonnummer in",
    },
  }, // -- тут же BE
  NO: {
    firstname: "Fornavn",
    lastname: "Etternavn",
    email: "Epostadresse",
    phone: "Telefonnummer",
    conditions: { 0: "I have read and accept the", 1: "Customer Agreement" },
    age: "I hereby confirm that I am at least 18 years old",
    button: "Start nå!",
    error: {
      required: "Dette er et obligatorisk felt",
      email: "Vennligst skriv inn en gyldig e-post adresse",
      phone: "Vennligst oppgi et gyldig telefonnummer",
    },
  },
  LT: {
    firstname: "Pirmas vardas",
    lastname: "Pavardė",
    email: "Elektroninio pašto adresas",
    phone: "Telefono numeris",
    conditions: { 0: "I have read and accept the", 1: "Customer Agreement" },
    age: "I hereby confirm that I am at least 18 years old",
    button: "Pradėk dabar!",
    error: {
      required: "Šis laukas yra privalomas",
      email: "Prašome įvesti galiojantį elektroninio pašto adresą",
      phone: "Įveskite galiojantį telefono numerį",
    },
  },
  PL: {
    title: "Rejestracja",
    firstname: "Imię",
    lastname: "Nazwisko",
    email: "E-mail",
    phone: "Numer telefonu",
    conditions: { 0: "I have read and accept the", 1: "Customer Agreement" },
    age: "I hereby confirm that I am at least 18 years old",
    button: "Zacząć teraz!",
    error: {
      required: "To pole jest wymagane",
      email: "Proszę wpisać aktualny adres e-mail",
      phone: "Proszę wpisać poprawny numer telefonu",
    },
  },
  CZ: {
    title: "Registrace",
    firstname: "Jméno",
    lastname: "Příjmení",
    email: "E-mail",
    phone: "Telefonní číslo",
    conditions: { 0: "I have read and accept the", 1: "Customer Agreement" },
    age: "I hereby confirm that I am at least 18 years old",
    button: "Začněte hned!",
    error: {
      required: "Toto je požadované pole",
      email: "Prosím zadejte platnou emailovou adresu",
      phone: "Vložte prosím platné telefonní číslo",
    },
  },
  PT: {
    firstname: "Primeiro nome",
    lastname: "Último nome",
    email: "O email",
    phone: "Número de telefone",
    conditions: { 0: "I have read and accept the", 1: "Customer Agreement" },
    age: "I hereby confirm that I am at least 18 years old",
    button: "Comece agora!",
    error: {
      required: "Este é um campo obrigatório",
      email: "Por favor insira um endereço de e-mail válido",
      phone: "Por favor insira um número de telefone válido",
    },
  },
  RU: {
    title: "Регистрация",
    firstname: "Имя",
    lastname: "Фамилия",
    email: "E-mail",
    phone: "Номер телефона",
    conditions: { 0: "I have read and accept the", 1: "Customer Agreement" },
    age: "I hereby confirm that I am at least 18 years old",
    button: "Начать сейчас!",
    error: {
      required: "Данное поле является обязательным к заполнению",
      email: "Пожалуйста, введите действительный адрес электронной почты",
      phone: "Пожалуйста, введите корректный телефонный номер",
    },
  }, // -- тут же LV, EE
  SE: {
    firstname: "Förnamn",
    lastname: "Efternamn",
    email: "E-postadress",
    phone: "Telefonnummer",
    conditions: { 0: "I have read and accept the", 1: "Customer Agreement" },
    age: "I hereby confirm that I am at least 18 years old",
    button: "Börja nu!",
    error: {
      required: "Detta är ett obligatoriskt fält",
      email: "Ange en giltig e-postadress",
      phone: "Var vänlig och slå in ett giltigt telefonnummer",
    },
  },
};
export default localization;
